branch-defaults:
  default:
    environment: udagram-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
environment-defaults:
  udagram-env:
    branch: null
    repository: null
global:
  application_name: udagram-app
  default_ec2_keyname: vockey
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
